require("plugins.octo")
require("plugins.vimtex")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.dap")
require("plugins.telescope")
require("plugins.no-neck-pain")
require("plugins.oil")
